### ISSUE TITLE
TODO and Issues with Archive Playback

### ISSUE THREAD

**Issue by geudrik** [geudrik/Bassdrive-Kodi-Plugin#5]
- [ ] Fix `&amp;` not being decoded when pulling filenames from the archives
- [ ] Set up a pre-flight routine that handles things like checking for cache files, populating them, etc
- [x] Prune empty folders (eg: 'Thursday' - 'Scenic Advisory Show')
